// <auto-generated />
using System;
using GACSE.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GACSE.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GACSE.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("MedicoId", "Fecha", "Hora");

                    b.ToTable("Citas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Programada",
                            Fecha = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 1,
                            Motivo = "Consulta general",
                            PacienteId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Programada",
                            Fecha = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 8, 20, 0, 0),
                            MedicoId = 1,
                            Motivo = "Dolor de cabeza frecuente",
                            PacienteId = 2
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Programada",
                            Fecha = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 9, 0, 0, 0),
                            MedicoId = 2,
                            Motivo = "Revisión cardiológica",
                            PacienteId = 4
                        },
                        new
                        {
                            Id = 4,
                            Estado = "Programada",
                            Fecha = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 10, 0, 0, 0),
                            MedicoId = 4,
                            Motivo = "Control pediátrico",
                            PacienteId = 3
                        },
                        new
                        {
                            Id = 5,
                            Estado = "Completada",
                            Fecha = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 9, 0, 0, 0),
                            MedicoId = 1,
                            Motivo = "Chequeo anual",
                            PacienteId = 5
                        });
                });

            modelBuilder.Entity("GACSE.Domain.Entities.HorarioMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "DiaSemana")
                        .IsUnique();

                    b.ToTable("HorariosMedicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaSemana = 1,
                            HoraFin = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 1
                        },
                        new
                        {
                            Id = 2,
                            DiaSemana = 2,
                            HoraFin = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 1
                        },
                        new
                        {
                            Id = 3,
                            DiaSemana = 3,
                            HoraFin = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 1
                        },
                        new
                        {
                            Id = 4,
                            DiaSemana = 4,
                            HoraFin = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 1
                        },
                        new
                        {
                            Id = 5,
                            DiaSemana = 5,
                            HoraFin = new TimeSpan(0, 12, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 1
                        },
                        new
                        {
                            Id = 6,
                            DiaSemana = 1,
                            HoraFin = new TimeSpan(0, 15, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            MedicoId = 2
                        },
                        new
                        {
                            Id = 7,
                            DiaSemana = 3,
                            HoraFin = new TimeSpan(0, 15, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            MedicoId = 2
                        },
                        new
                        {
                            Id = 8,
                            DiaSemana = 5,
                            HoraFin = new TimeSpan(0, 13, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            MedicoId = 2
                        },
                        new
                        {
                            Id = 9,
                            DiaSemana = 2,
                            HoraFin = new TimeSpan(0, 13, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 7, 0, 0, 0),
                            MedicoId = 3
                        },
                        new
                        {
                            Id = 10,
                            DiaSemana = 4,
                            HoraFin = new TimeSpan(0, 13, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 7, 0, 0, 0),
                            MedicoId = 3
                        },
                        new
                        {
                            Id = 11,
                            DiaSemana = 1,
                            HoraFin = new TimeSpan(0, 16, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 4
                        },
                        new
                        {
                            Id = 12,
                            DiaSemana = 2,
                            HoraFin = new TimeSpan(0, 16, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 4
                        },
                        new
                        {
                            Id = 13,
                            DiaSemana = 3,
                            HoraFin = new TimeSpan(0, 16, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 4
                        },
                        new
                        {
                            Id = 14,
                            DiaSemana = 4,
                            HoraFin = new TimeSpan(0, 16, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 4
                        },
                        new
                        {
                            Id = 15,
                            DiaSemana = 5,
                            HoraFin = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            MedicoId = 4
                        });
                });

            modelBuilder.Entity("GACSE.Domain.Entities.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidad = "MedicinaGeneral",
                            Nombre = "Dr. Carlos García"
                        },
                        new
                        {
                            Id = 2,
                            Especialidad = "Cardiologia",
                            Nombre = "Dra. María López"
                        },
                        new
                        {
                            Id = 3,
                            Especialidad = "Cirugia",
                            Nombre = "Dr. Roberto Sánchez"
                        },
                        new
                        {
                            Id = 4,
                            Especialidad = "Pediatria",
                            Nombre = "Dra. Ana Martínez"
                        });
                });

            modelBuilder.Entity("GACSE.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorreoElectronico = "juan.perez@email.com",
                            FechaNacimiento = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan Pérez",
                            Telefono = "5551234567"
                        },
                        new
                        {
                            Id = 2,
                            CorreoElectronico = "maria.rodriguez@email.com",
                            FechaNacimiento = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María Rodríguez",
                            Telefono = "5559876543"
                        },
                        new
                        {
                            Id = 3,
                            CorreoElectronico = "pedro.hernandez@email.com",
                            FechaNacimiento = new DateTime(2015, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro Hernández",
                            Telefono = "5554567890"
                        },
                        new
                        {
                            Id = 4,
                            CorreoElectronico = "laura.gomez@email.com",
                            FechaNacimiento = new DateTime(1978, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura Gómez",
                            Telefono = "5557891234"
                        },
                        new
                        {
                            Id = 5,
                            CorreoElectronico = "carlos.diaz@email.com",
                            FechaNacimiento = new DateTime(2000, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos Díaz",
                            Telefono = "5552345678"
                        },
                        new
                        {
                            Id = 6,
                            CorreoElectronico = "ana.torres@email.com",
                            FechaNacimiento = new DateTime(1995, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana Torres",
                            Telefono = "5558765432"
                        });
                });

            modelBuilder.Entity("GACSE.Domain.Entities.Cita", b =>
                {
                    b.HasOne("GACSE.Domain.Entities.Medico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GACSE.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GACSE.Domain.Entities.HorarioMedico", b =>
                {
                    b.HasOne("GACSE.Domain.Entities.Medico", "Medico")
                        .WithMany("Horarios")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("GACSE.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("GACSE.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
